Add html, css and a readme files and a linter for HTML and CSS
SFarida/Hello-Microverse pull request #2
Opened 2022-11-29 21:35 UTC by SFarida

This is the branch that will be used for development and it includes:

- Added a .gitignore file with node_modules, and test.me.
- Added a linter for HTML and CSS.
- Added a README file together with an html and a css file.

2022-11-29 23:25 UTC, rskinnerc requested changes
Hi @SFarida  👋,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/26911718/204670504-727a60a6-8672-4863-b3f0-6d63bfdcd0d8.gif)


 ## Highlights
- Good job adding the big `node_modules` to `.gitignore`
- Awesome! You set up GitHub actions rightly

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- 🔴 Dear @SFarida please note that you don't need to create separate pull requests whenever a code reviewer asks you for changes. You can keep working on the same branch and push commits to that branch. The PR gets updated automatically. Having said that, this is a Re-review of the #1 Pull Request previously submitted.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 23:25 UTC, rskinnerc commented on README.md
>  Apply GitHub flow best practices and provide a good documentation
Hey there @SFarida good job with your project so far 😃😃. 

[OPTIONAL] Please consider removing this line. Following the recommended template would make look your project more professional.

2022-11-29 23:25 UTC, rskinnerc commented on README.md
> +</div>
[OPTIONAL] Please consider removing the default Microverse logo or updating it to your custom logo. 🖼️

2022-11-29 23:25 UTC, rskinnerc commented on README.md
> +</details>
♻️ Awesome job adding the missing sections to the README file as requested by the previous CR ✌️✌️. However, there are still some changes that need your attention.

- [ ] The main technologies for this project would be HTML and CSS. Please update the technologies list accordingly. You can also add the linters. 🤖

2022-11-29 23:25 UTC, rskinnerc commented on README.md
> +👤 **Author1**
♻️ Great job. Your README file looks more professional with the added sections. However, those sections need a little bit more customization. Customizing to your needs/info makes your repo even more professional.

- [ ] Please change _Author1_ to your name.
- [ ] You added the required sections to the README. However, customizing them as per the project features would be awesome. Kindly update so the users have a better picture of how to use this repo (i.e. in the getting started section, explain how to clone the repo, how to start the project and use it) 📋📋📋

2022-11-29 23:25 UTC, rskinnerc commented on README.md
> +This project is [MIT](./LICENSE) licensed.
♻️ Amazing! You added a license to your project 🔏🔏. However, seems like it is pointing to a broken link. 

- [ ] Please fix the path and add the license file you want to use. [This template](https://github.com/microverseinc/readme-template) contains an MIT license template that you can make use of. Kindly update it accordingly.

2022-11-29 23:25 UTC, rskinnerc commented on .github/workflows/linters.yml
> +name: Linters
[OPTIONAL] Even though this is an optional (but highly recommended) change, bear in mind that for **every future project** you will need to set up the linters.

You have done great work setting up GitHub Actions (this file) 💪💪💪. But as part of the good practices and setting up the linters, you must install and configure (add config files) the linters to your project. Please check [this guide on how to set up your HTML/CSS Linters.](https://github.com/microverseinc/linters-config/tree/master/html-css)

2022-11-29 23:25 UTC, rskinnerc commented on index.html
> +    <link rel="stylesheet" href="index.css">
[OPTIONAL] Please consider adding a `title` to your project. Making this habit would make you a better dev. 😃😃😃

2022-11-30 09:36 UTC, SFarida commented
Hello, in one of the required changes I was suppose to rename my branch and while doing so the pull request changed. Please if there's a way to change a branch without changing the pull request let me know.

2022-11-30 20:11 UTC, brainconnect93 approved these changes
### Hi @SFarida, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif">

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 
- Files properly ignored  🥇 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 23:47 UTC, merged